import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/Header";
import { Navigation } from "./components/Navigation";
import { RecoilRootWrapper } from "./components/RecoilRootWrapper";
import { SideDrawer } from "./components/SideDrawer";
import { Zen_Kaku_Gothic_New } from "next/font/google";

export const font = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "flully | 散歩記録型まいごペット捜索支援",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={`${font.className} antialiased`}>
        <RecoilRootWrapper>
          <SideDrawer>
            <Header />
            <div className="lg:pl-16 lb:pb-0 w-full">{children}</div>
            <Navigation />
          </SideDrawer>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
